version: '3'

services:
  web:
    image: python:3.9
    container_name: django_web
    command: bash -c "pip install django && cd /code && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"

  db:
    image: postgres
    container_name: django_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=$ENV_POSTGRES_DB
      - POSTGRES_USER=$ENV_POSTGRES_USER
      - POSTGRES_PASSWORD=$ENV_POSTGRES_PASSWORD
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:






