# Generated by Django 4.2.3 on 2023-07-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dota_item_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('appearance_time', models.TimeField(verbose_name='Время появления')),
                ('discription', models.TextField(verbose_name='Описание предмета')),
            ],
        ),
    ]
