# Generated by Django 4.2.3 on 2023-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servises_in_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('guid_server', models.CharField(max_length=100, verbose_name='Guid')),
                ('appearance_time', models.DateField(verbose_name='Дата Принятия в поддержку')),
                ('discription', models.TextField(verbose_name='Дополнительная информация, документация')),
            ],
        ),
    ]
