# Generated by Django 4.2.3 on 2023-07-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamining', '0002_servises_in_support'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servises_in_support',
            new_name='ServisesInSupport',
        ),
    ]
